/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteDotwebmanifestRouteImport } from './routes/site[.]webmanifest'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReturnsPolicyRouteImport } from './routes/returns-policy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as NewArrivalsRouteImport } from './routes/new-arrivals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeControlsRouteImport } from './routes/home-controls'
import { Route as GotAQuestionRouteImport } from './routes/got-a-question'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DeliveryInformationRouteImport } from './routes/delivery-information'
import { Route as CreditAccountRouteImport } from './routes/credit-account'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ControlPanelsSoftwareRouteImport } from './routes/control-panels-software'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as ConcreteRouteImport } from './routes/concrete'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AsphaltRouteImport } from './routes/asphalt'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductsHandleRouteImport } from './routes/products/$handle'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminChangePasswordRouteImport } from './routes/admin/change-password'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminSubmissionsIndexRouteImport } from './routes/admin/submissions.index'
import { Route as AdminContentIndexRouteImport } from './routes/admin/content.index'
import { Route as ContentMediaIdFilenameRouteImport } from './routes/content-media/$id/$filename'
import { Route as AdminSubmissionsIdRouteImport } from './routes/admin/submissions.$id'
import { Route as AdminContentKeyRouteImport } from './routes/admin/content.$key'
import { Route as AdminContentKeyPreviewRouteImport } from './routes/admin/content.$key.preview'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteDotwebmanifestRoute = SiteDotwebmanifestRouteImport.update({
  id: '/site.webmanifest',
  path: '/site.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsPolicyRoute = ReturnsPolicyRouteImport.update({
  id: '/returns-policy',
  path: '/returns-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const NewArrivalsRoute = NewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeControlsRoute = HomeControlsRouteImport.update({
  id: '/home-controls',
  path: '/home-controls',
  getParentRoute: () => rootRouteImport,
} as any)
const GotAQuestionRoute = GotAQuestionRouteImport.update({
  id: '/got-a-question',
  path: '/got-a-question',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryInformationRoute = DeliveryInformationRouteImport.update({
  id: '/delivery-information',
  path: '/delivery-information',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditAccountRoute = CreditAccountRouteImport.update({
  id: '/credit-account',
  path: '/credit-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPanelsSoftwareRoute = ControlPanelsSoftwareRouteImport.update({
  id: '/control-panels-software',
  path: '/control-panels-software',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcreteRoute = ConcreteRouteImport.update({
  id: '/concrete',
  path: '/concrete',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AsphaltRoute = AsphaltRouteImport.update({
  id: '/asphalt',
  path: '/asphalt',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/admin/change-password',
  path: '/admin/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsIndexRoute = AdminSubmissionsIndexRouteImport.update({
  id: '/admin/submissions/',
  path: '/admin/submissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/admin/content/',
  path: '/admin/content/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentMediaIdFilenameRoute = ContentMediaIdFilenameRouteImport.update({
  id: '/content-media/$id/$filename',
  path: '/content-media/$id/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsIdRoute = AdminSubmissionsIdRouteImport.update({
  id: '/admin/submissions/$id',
  path: '/admin/submissions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentKeyRoute = AdminContentKeyRouteImport.update({
  id: '/admin/content/$key',
  path: '/admin/content/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentKeyPreviewRoute = AdminContentKeyPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminContentKeyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/asphalt': typeof AsphaltRoute
  '/automation': typeof AutomationRoute
  '/cart': typeof CartRoute
  '/concrete': typeof ConcreteRoute
  '/contact-us': typeof ContactUsRoute
  '/control-panels-software': typeof ControlPanelsSoftwareRoute
  '/cookies': typeof CookiesRoute
  '/credit-account': typeof CreditAccountRoute
  '/delivery-information': typeof DeliveryInformationRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/got-a-question': typeof GotAQuestionRoute
  '/home-controls': typeof HomeControlsRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/packing': typeof PackingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/returns': typeof ReturnsRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-order': typeof TrackOrderRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/content/$key': typeof AdminContentKeyRouteWithChildren
  '/admin/submissions/$id': typeof AdminSubmissionsIdRoute
  '/content-media/$id/$filename': typeof ContentMediaIdFilenameRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
  '/admin/content/$key/preview': typeof AdminContentKeyPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/asphalt': typeof AsphaltRoute
  '/automation': typeof AutomationRoute
  '/cart': typeof CartRoute
  '/concrete': typeof ConcreteRoute
  '/contact-us': typeof ContactUsRoute
  '/control-panels-software': typeof ControlPanelsSoftwareRoute
  '/cookies': typeof CookiesRoute
  '/credit-account': typeof CreditAccountRoute
  '/delivery-information': typeof DeliveryInformationRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/got-a-question': typeof GotAQuestionRoute
  '/home-controls': typeof HomeControlsRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/packing': typeof PackingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/returns': typeof ReturnsRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-order': typeof TrackOrderRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/admin': typeof AdminIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/content/$key': typeof AdminContentKeyRouteWithChildren
  '/admin/submissions/$id': typeof AdminSubmissionsIdRoute
  '/content-media/$id/$filename': typeof ContentMediaIdFilenameRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/admin/submissions': typeof AdminSubmissionsIndexRoute
  '/admin/content/$key/preview': typeof AdminContentKeyPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/asphalt': typeof AsphaltRoute
  '/automation': typeof AutomationRoute
  '/cart': typeof CartRoute
  '/concrete': typeof ConcreteRoute
  '/contact-us': typeof ContactUsRoute
  '/control-panels-software': typeof ControlPanelsSoftwareRoute
  '/cookies': typeof CookiesRoute
  '/credit-account': typeof CreditAccountRoute
  '/delivery-information': typeof DeliveryInformationRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/got-a-question': typeof GotAQuestionRoute
  '/home-controls': typeof HomeControlsRoute
  '/login': typeof LoginRoute
  '/new-arrivals': typeof NewArrivalsRoute
  '/packing': typeof PackingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/returns': typeof ReturnsRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/site.webmanifest': typeof SiteDotwebmanifestRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track-order': typeof TrackOrderRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/admin/': typeof AdminIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/content/$key': typeof AdminContentKeyRouteWithChildren
  '/admin/submissions/$id': typeof AdminSubmissionsIdRoute
  '/content-media/$id/$filename': typeof ContentMediaIdFilenameRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/admin/submissions/': typeof AdminSubmissionsIndexRoute
  '/admin/content/$key/preview': typeof AdminContentKeyPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/account'
    | '/asphalt'
    | '/automation'
    | '/cart'
    | '/concrete'
    | '/contact-us'
    | '/control-panels-software'
    | '/cookies'
    | '/credit-account'
    | '/delivery-information'
    | '/disclaimer'
    | '/forgot-password'
    | '/got-a-question'
    | '/home-controls'
    | '/login'
    | '/new-arrivals'
    | '/packing'
    | '/privacy-policy'
    | '/quote'
    | '/register'
    | '/resources'
    | '/returns'
    | '/returns-policy'
    | '/robots.txt'
    | '/search'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track-order'
    | '/unsubscribe'
    | '/admin/activity'
    | '/admin/change-password'
    | '/admin/login'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/users'
    | '/products/$handle'
    | '/admin/'
    | '/products/'
    | '/admin/content/$key'
    | '/admin/submissions/$id'
    | '/content-media/$id/$filename'
    | '/admin/content/'
    | '/admin/submissions/'
    | '/admin/content/$key/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/account'
    | '/asphalt'
    | '/automation'
    | '/cart'
    | '/concrete'
    | '/contact-us'
    | '/control-panels-software'
    | '/cookies'
    | '/credit-account'
    | '/delivery-information'
    | '/disclaimer'
    | '/forgot-password'
    | '/got-a-question'
    | '/home-controls'
    | '/login'
    | '/new-arrivals'
    | '/packing'
    | '/privacy-policy'
    | '/quote'
    | '/register'
    | '/resources'
    | '/returns'
    | '/returns-policy'
    | '/robots.txt'
    | '/search'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track-order'
    | '/unsubscribe'
    | '/admin/activity'
    | '/admin/change-password'
    | '/admin/login'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/users'
    | '/products/$handle'
    | '/admin'
    | '/products'
    | '/admin/content/$key'
    | '/admin/submissions/$id'
    | '/content-media/$id/$filename'
    | '/admin/content'
    | '/admin/submissions'
    | '/admin/content/$key/preview'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/account'
    | '/asphalt'
    | '/automation'
    | '/cart'
    | '/concrete'
    | '/contact-us'
    | '/control-panels-software'
    | '/cookies'
    | '/credit-account'
    | '/delivery-information'
    | '/disclaimer'
    | '/forgot-password'
    | '/got-a-question'
    | '/home-controls'
    | '/login'
    | '/new-arrivals'
    | '/packing'
    | '/privacy-policy'
    | '/quote'
    | '/register'
    | '/resources'
    | '/returns'
    | '/returns-policy'
    | '/robots.txt'
    | '/search'
    | '/site.webmanifest'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/track-order'
    | '/unsubscribe'
    | '/admin/activity'
    | '/admin/change-password'
    | '/admin/login'
    | '/admin/media'
    | '/admin/settings'
    | '/admin/users'
    | '/products/$handle'
    | '/admin/'
    | '/products/'
    | '/admin/content/$key'
    | '/admin/submissions/$id'
    | '/content-media/$id/$filename'
    | '/admin/content/'
    | '/admin/submissions/'
    | '/admin/content/$key/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AccountRoute: typeof AccountRoute
  AsphaltRoute: typeof AsphaltRoute
  AutomationRoute: typeof AutomationRoute
  CartRoute: typeof CartRoute
  ConcreteRoute: typeof ConcreteRoute
  ContactUsRoute: typeof ContactUsRoute
  ControlPanelsSoftwareRoute: typeof ControlPanelsSoftwareRoute
  CookiesRoute: typeof CookiesRoute
  CreditAccountRoute: typeof CreditAccountRoute
  DeliveryInformationRoute: typeof DeliveryInformationRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GotAQuestionRoute: typeof GotAQuestionRoute
  HomeControlsRoute: typeof HomeControlsRoute
  LoginRoute: typeof LoginRoute
  NewArrivalsRoute: typeof NewArrivalsRoute
  PackingRoute: typeof PackingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QuoteRoute: typeof QuoteRoute
  RegisterRoute: typeof RegisterRoute
  ResourcesRoute: typeof ResourcesRoute
  ReturnsRoute: typeof ReturnsRoute
  ReturnsPolicyRoute: typeof ReturnsPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SiteDotwebmanifestRoute: typeof SiteDotwebmanifestRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  AdminContentKeyRoute: typeof AdminContentKeyRouteWithChildren
  AdminSubmissionsIdRoute: typeof AdminSubmissionsIdRoute
  ContentMediaIdFilenameRoute: typeof ContentMediaIdFilenameRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
  AdminSubmissionsIndexRoute: typeof AdminSubmissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site.webmanifest': {
      id: '/site.webmanifest'
      path: '/site.webmanifest'
      fullPath: '/site.webmanifest'
      preLoaderRoute: typeof SiteDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-policy': {
      id: '/returns-policy'
      path: '/returns-policy'
      fullPath: '/returns-policy'
      preLoaderRoute: typeof ReturnsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-arrivals': {
      id: '/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof NewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-controls': {
      id: '/home-controls'
      path: '/home-controls'
      fullPath: '/home-controls'
      preLoaderRoute: typeof HomeControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/got-a-question': {
      id: '/got-a-question'
      path: '/got-a-question'
      fullPath: '/got-a-question'
      preLoaderRoute: typeof GotAQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-information': {
      id: '/delivery-information'
      path: '/delivery-information'
      fullPath: '/delivery-information'
      preLoaderRoute: typeof DeliveryInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-account': {
      id: '/credit-account'
      path: '/credit-account'
      fullPath: '/credit-account'
      preLoaderRoute: typeof CreditAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-panels-software': {
      id: '/control-panels-software'
      path: '/control-panels-software'
      fullPath: '/control-panels-software'
      preLoaderRoute: typeof ControlPanelsSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concrete': {
      id: '/concrete'
      path: '/concrete'
      fullPath: '/concrete'
      preLoaderRoute: typeof ConcreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asphalt': {
      id: '/asphalt'
      path: '/asphalt'
      fullPath: '/asphalt'
      preLoaderRoute: typeof AsphaltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/admin/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions/': {
      id: '/admin/submissions/'
      path: '/admin/submissions'
      fullPath: '/admin/submissions/'
      preLoaderRoute: typeof AdminSubmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/admin/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-media/$id/$filename': {
      id: '/content-media/$id/$filename'
      path: '/content-media/$id/$filename'
      fullPath: '/content-media/$id/$filename'
      preLoaderRoute: typeof ContentMediaIdFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions/$id': {
      id: '/admin/submissions/$id'
      path: '/admin/submissions/$id'
      fullPath: '/admin/submissions/$id'
      preLoaderRoute: typeof AdminSubmissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/$key': {
      id: '/admin/content/$key'
      path: '/admin/content/$key'
      fullPath: '/admin/content/$key'
      preLoaderRoute: typeof AdminContentKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content/$key/preview': {
      id: '/admin/content/$key/preview'
      path: '/preview'
      fullPath: '/admin/content/$key/preview'
      preLoaderRoute: typeof AdminContentKeyPreviewRouteImport
      parentRoute: typeof AdminContentKeyRoute
    }
  }
}

interface AdminContentKeyRouteChildren {
  AdminContentKeyPreviewRoute: typeof AdminContentKeyPreviewRoute
}

const AdminContentKeyRouteChildren: AdminContentKeyRouteChildren = {
  AdminContentKeyPreviewRoute: AdminContentKeyPreviewRoute,
}

const AdminContentKeyRouteWithChildren = AdminContentKeyRoute._addFileChildren(
  AdminContentKeyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccountRoute: AccountRoute,
  AsphaltRoute: AsphaltRoute,
  AutomationRoute: AutomationRoute,
  CartRoute: CartRoute,
  ConcreteRoute: ConcreteRoute,
  ContactUsRoute: ContactUsRoute,
  ControlPanelsSoftwareRoute: ControlPanelsSoftwareRoute,
  CookiesRoute: CookiesRoute,
  CreditAccountRoute: CreditAccountRoute,
  DeliveryInformationRoute: DeliveryInformationRoute,
  DisclaimerRoute: DisclaimerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GotAQuestionRoute: GotAQuestionRoute,
  HomeControlsRoute: HomeControlsRoute,
  LoginRoute: LoginRoute,
  NewArrivalsRoute: NewArrivalsRoute,
  PackingRoute: PackingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QuoteRoute: QuoteRoute,
  RegisterRoute: RegisterRoute,
  ResourcesRoute: ResourcesRoute,
  ReturnsRoute: ReturnsRoute,
  ReturnsPolicyRoute: ReturnsPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SiteDotwebmanifestRoute: SiteDotwebmanifestRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TrackOrderRoute: TrackOrderRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  AdminIndexRoute: AdminIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  AdminContentKeyRoute: AdminContentKeyRouteWithChildren,
  AdminSubmissionsIdRoute: AdminSubmissionsIdRoute,
  ContentMediaIdFilenameRoute: ContentMediaIdFilenameRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
  AdminSubmissionsIndexRoute: AdminSubmissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
